# Generated by Django 5.2.7 on 2025-11-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Img',
        ),
    ]
