# Generated by Django 5.2.7 on 2025-11-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_blog_author_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
